#!/bin/sh

echo "# Generated by docker-entrypoint.sh
admin:
  host: ${ONLINECONF_ADMIN_HOST}
  port: ${ONLINECONF_ADMIN_PORT}
  username: ${ONLINECONF_UPDATER_USER}
  password: ${ONLINECONF_UPDATER_PASSWORD}
data_dir: /usr/local/etc/onlineconf/
update_interval: ${ONLINECONF_UPDATE_INTERVAL:-10}
" > /usr/local/etc/onlineconf.yaml

exec /usr/local/bin/onlineconf-updater
