#!/bin/bash

echo "Start diff" >> /var/log/onlineconf-diff.log

for i in $(ls /usr/local/etc/onlineconf/); do
    diff -I '#.*' /usr/local/etc/onlineconf/$i /usr/local/etc/onlineconf2/$i >> /var/log/onlineconf-diff.log
done
